modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://www.curseforge.com/members/azuredoomc/followers"
logoFile="doomlogo.png"
[[mods]] 
modId="doomweapon"
version="${file.jarVersion}" 
displayName="Doom Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/doom-crucible" 
authors="AzureDoomC" 
credits="Thanks to Narial/ulnight for the awesome model and textures!"
description='''
Adds Doom into Minecraft
'''